// テスト用のデータ

import { Article } from '@/types/database';

const DemoData: Article[] = [
    {
        Id: 1,
        Title: '!!!@@DemoDeta1',
        UserId: 1,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．',
        SeriesId: 1,
        Body: 'DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．DemoDetaです．',
        GroupId: 1,
        CreateAt: '2024.3.20',
    },
    {
        Id: 2,
        Title: '!!!@@DemoDeta2',
        UserId: 2,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．',
        SeriesId: 2,
        Body: 'DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．DemoDeta2です．',
        GroupId: 2,
        CreateAt: '2024.3.21',
    },
    {
        Id: 3,
        Title: '!!!DemoDeta3',
        UserId: 3,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．',
        SeriesId: 3,
        Body: 'DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．DemoDeta3です．',
        GroupId: 3,
        CreateAt: '2024.3.22',
    },
    {
        Id: 4,
        Title: '???DemoDeta4',
        UserId: 4,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．',
        SeriesId: 4,
        Body: 'DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．DemoDeta4です．',
        GroupId: 4,
        CreateAt: '2024.3.23',
    },
    {
        Id: 5,
        Title: '???DemoDeta5',
        UserId: 5,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．',
        SeriesId: 5,
        Body: 'DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．DemoDeta5です．',
        GroupId: 5,
        CreateAt: '2024.3.24',
    },
    {
        Id: 6,
        Title: '???DemoDeta6',
        UserId: 6,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．',
        SeriesId: 6,
        Body: 'DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．DemoDeta6です．',
        GroupId: 6,
        CreateAt: '2024.3.25',
    },
    {
        Id: 7,
        Title: '???DemoDeta7',
        UserId: 7,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．',
        SeriesId: 7,
        Body: 'DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．DemoDeta7です．',
        GroupId: 7,
        CreateAt: '2024.3.26',
    },
    {
        Id: 8,
        Title: '!!!@@DemoDeta8',
        UserId: 8,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．',
        SeriesId: 8,
        Body: 'DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．DemoDeta8です．',
        GroupId: 8,
        CreateAt: '2024.3.27',
    },
    {
        Id: 9,
        Title: '!!!@@DemoDeta9',
        UserId: 9,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．',
        SeriesId: 9,
        Body: 'DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．DemoDeta9です．',
        GroupId: 9,
        CreateAt: '2024.3.28',
    },
    {
        Id: 10,
        Title: '!!!DemoDeta10',
        UserId: 10,
        Thumbnail: 'img/currentEventDemo.svg',
        Description: 'DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．',
        SeriesId: 10,
        Body: 'DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．DemoDeta10です．',
        GroupId: 10,
        CreateAt: '2024.3.29',
    }

]

export default DemoData;
