name: vercel deploy hooks

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Call the web hook
      run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOKS }}
